include Makefile.variables

all:

MLI=unicode.mli
MLSRC=unicode.ml
MLINIT=
CSRC=

LIBNAME=unicode
STUBLIBNAME=

OCAMLCFLAGS=-w +a
CFLAGS=

CCLIB=
LDFLAGS=
LDLIB=

$(BUILDDIR)/unicode.cmo: $(BUILDDIR)/unicode.cmi
$(BUILDDIR)/unicode.cmx: $(BUILDDIR)/unicode.cmi

include Makefile.rules
